%% original data generation _ A matrix has small value
clear
clc
close all

% d = 100; %dimension
% T = 53; %sample size

% Import adaptive Lasso estimator generated by R 
W = readmatrix('path to estimated transition matrix');

W(1,:) = [];
W(:,1) = [];
W_ = W;
W_ = max(W_, W_');

%  W_ = A;
% cspy(W_)

D = diag(sum(W_,2) + 1e-20);
L = D - W_; %unormalized Laplacian
sum_W = sum(W_,2).^(-0.5);
D_new = diag(sum(W_,2).^(-0.5)); D_new(isinf(D_new)) = max(sum_W(~isinf(sum_W))) + 1;
L_new = D_new * L * D_new;
L_new = (L_new + L_new')/2;
[evc, evl] = eig(L_new); %each column of evc is an eigenvector

[d,ind] = sort(abs(diag(evl))); % sort eigen value in aescending order
evl_new = evl(ind,ind); 
evc_new = evc(:,ind);

idx = find(abs(diag(evl_new))<=10);

silhouette_score = [];
for k = 2:1:50
    disp(k)
    input = evc_new(:,idx(1:k));
    
    dim_input = size(input);
    row_sum_input = [];
    % calculate row sum_squared
    for j = 1:dim_input(1)
        row_sum = 0;
        for i = 1:dim_input(2)
            row_sum = row_sum + input(j,i)^2;
        end
        row_sum_input(j) = row_sum^(0.5);
    end
    
    T_norm = input;
    % form the matrix T from input
    for j = 1:dim_input(1)
        for i = 1:dim_input(2)
            T_norm(j,i) = input(j,i) / row_sum_input(j);
        end
    end
    T_norm(isnan(T_norm))=0;

%                cspy(L_new);

    c_idx = kmeans(T_norm,k);
%                c_idx = kmeans(input,k);
%                hist(c_idx, k);
%                h_idx = clusterdata(T, k);
%                hist(h_idx, k);
    s_score = mean(silhouette(T_norm, c_idx));
    silhouette_score = [silhouette_score; s_score];
end

x_array = 2:1:50;
plot(x_array, silhouette_score);

k = 7;
input = evc_new(:,idx(1:k));
    
    dim_input = size(input);
    row_sum_input = [];
    % calculate row sum_squared
    for j = 1:dim_input(1)
        row_sum = 0;
        for i = 1:dim_input(2)
            row_sum = row_sum + input(j,i)^2;
        end
        row_sum_input(j) = row_sum^(0.5);
    end
    
    T_norm = input;
    % form the matrix T from input
    for j = 1:dim_input(1)
        for i = 1:dim_input(2)
            T_norm(j,i) = input(j,i) / row_sum_input(j);
        end
    end
    T_norm(isnan(T_norm))=0;

%                cspy(L_new);

    c_idx = kmeans(T_norm,k);
[s,h] = silhouette(T_norm, c_idx);
hist(c_idx, k)

% save cluster result
writematrix(c_idx,'path to clustering result');

